### ISSUE TITLE
SV2 Pool Continues Working on Downstream Disconnect, But Still Prints Panic Message

### ISSUE THREAD

**Issue by rrybarczyk** [stratum-mining/stratum#263]
Pool restarts on proxy disconnect + reconnect. It is working, BUT the pool does print a panic:
```
thread 'tokio-runtime-worker' panicked at 'explicit panic', /root/Dev/stratum/utils/network-helpers/src/noise_connection_tokio.rs:66:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'explicit panic', /root/Dev/stratum/utils/network-helpers/src/noise_connection_tokio.rs:98:25
```

Should figure out how to handle this more gracefully.

**Comment by rrybarczyk** [comment]
Panics are useful because they indicate when a task is dropped. 

After we have the `message-generator` mocks done, and can use them for integration tests, we can explore this panic more. We may want to keep this panic, or perhaps find a more graceful way to indicate a dropped task.
