### ISSUE TITLE
TProxy Incompatible with SRI Pool

### ISSUE THREAD

**Issue by rrybarczyk** [stratum-mining/stratum#356]
The last ~15% of the translator proxy MVP1 was developed solely against Braiins pool. It is not compatible with SRI's pool and the following error occurs on upstream connection (errors before any downstreams connect):

Tproxy error:
```
Finished dev [unoptimized + debuginfo] target(s) in 0.08s
 Running `/root/Dev/stratum/target/debug/translator`
2022-11-24T00:14:47.561525Z  INFO translator: PC: ProxyConfig { upstream_address: "127.0.0.1", upstream_port: 34254, upstream_authority_pubkey: "2di19GHYQnAZJmEpoUeP7C3Eg9TCcksHr23rZCC83dvUiZgiDL", downstream_address: "0.0.0.0", downstream_port: 34255, max_supported_version: 2, min_supported_version: 2, min_extranonce2_size: 16 }
2022-11-24T00:14:47.562425Z  INFO translator::upstream_sv2::upstream: PROXY SERVER - ACCEPTING FROM UPSTREAM: 127.0.0.1:34254
2022-11-24T00:14:47.573064Z  INFO translator::upstream_sv2::upstream: Up: Sending: SetupConnection { protocol: MiningProtocol, min_version: 2, max_version: 2, flags: 14, endpoint_host: Owned([48, 46, 48, 46, 48, 46, 48]), endpoint_port: 50, vendor: Owned([]), hardware_version: Owned([]), firmware: Owned([]), device_id: Owned([]) }
2022-11-24T00:14:47.574624Z  INFO translator::upstream_sv2::upstream: Up: Receiving: Sv2Frame { header: Header { extension_type: 0, msg_type: 1, msg_length: U24(6) }, payload: None, serialized: Some(Slice { offset: 0x7f0a4d7dd010, len: 12, index: 1, shared_state: SharedState(128), owned: None }) }
2022-11-24T00:14:47.574708Z  INFO translator::upstream_sv2::upstream: Up: Sending: OpenExtendedMiningChannel(OpenExtendedMiningChannel { request_id: 0, user_identity: Owned([65, 66, 67]), nominal_hash_rate: 10000000000.0, max_target: Owned([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 255, 255, 255, 255, 255, 255, 255, 255]), min_extranonce_size: 16 })
2022-11-24T00:14:47.576230Z  INFO translator::upstream_sv2::upstream: Is future job: false

2022-11-24T00:14:47.576323Z  INFO translator::upstream_sv2::upstream: Up: New Extended Mining Job
2022-11-24T00:14:47.576468Z ERROR translator::proxy::next_mining_notify: Job Id Mismatch. SetNewPrevHash Job Id: None, NewExtendedMiningJob Job Id: Some(1)
2022-11-24T00:14:47.576477Z  INFO translator::upstream_sv2::upstream: Up: Set New Prev Hash
2022-11-24T00:14:47.576505Z ERROR translator::proxy::bridge: NewExtendedMiningJob and SetNewPrevHash job ids mismatch
thread 'async-std/runtime' panicked at 'NewExtendedMiningJob and SetNewPrevHash job ids mismatch', roles/translator/src/proxy/bridge.rs:335:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

SRI pool error:
```
    Finished dev [unoptimized + debuginfo] target(s) in 8.77s
     Running `/root/Dev/stratum/target/debug/pool`
2022-11-24T00:13:05.284973Z  INFO pool: Pool INITIALIZING with config: "pool-config.toml"
2022-11-24T00:13:05.285209Z  INFO pool::lib::template_receiver: Connected to template distribution server at 127.0.0.1:8442
2022-11-24T00:13:05.335579Z  INFO pool::lib::template_receiver::setup_connection: Setup template provider connection success!
2022-11-24T00:13:05.375790Z  INFO pool::lib::mining_pool: Starting up pool listener
2022-11-24T00:13:05.375999Z  INFO pool::lib::mining_pool: Listening on 127.0.0.1:34254
2022-11-24T00:13:20.463753Z  INFO noise_sv2: -> suggested algorithms received [ChaChaPoly, AesGcm]
2022-11-24T00:13:20.476580Z ERROR roles_logic_sv2::utils: ERROR: I/O error: failed to fill whole buffer
thread 'tokio-runtime-worker' panicked at 'Merkle root failed to be calculated', roles/v2/pool/src/lib/mining_pool/mod.rs:65:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2022-11-24T00:13:58.867277Z ERROR network_helpers::noise_connection_tokio: Disconnected from client: early eof
2022-11-24T00:14:47.563518Z  INFO noise_sv2: -> suggested algorithms received [ChaChaPoly, AesGcm]
2022-11-24T00:14:47.575510Z ERROR roles_logic_sv2::utils: ERROR: I/O error: failed to fill whole buffer
thread 'tokio-runtime-worker' panicked at 'Merkle root failed to be calculated', roles/v2/pool/src/lib/mining_pool/mod.rs:65:10
```

**Comment by coleFD** [comment]
Linking this here since it relates to the 'Merkle root failed to be calculated' error 
https://github.com/stratum-mining/stratum/issues/317

**Comment by Fi3** [comment]
closed by https://github.com/stratum-mining/stratum/pull/391
