### ISSUE TITLE
Handle upstream disconnect

### ISSUE THREAD

**Issue by Sjors** [stratum-mining/stratum#407]
When running the translator sometimes it doesn't submit any shares upstream for a while. This seems to cause Braiins pool to disconnect, resulting in a panick:

```
2023-01-11T16:46:39.014204Z  INFO translator::upstream_sv2::upstream: Up: New Extended Mining Job
2023-01-11T16:46:39.020551Z  INFO translator::upstream_sv2::upstream: Up: Set New Prev Hash
2023-01-11T16:46:39.021994Z  INFO translator::downstream_sv1::downstream: Sending to Mining Device: "{\"method\":\"mining.notify\",\"params\":[\"10\",\"f13551f6ce34a054c8d54c1c1c42e7fdc5f8c0d40004de220000000000000000\",\"01000000010000000000000000000000000000000000000000000000000000000000000000ffffffff4b038cc50bfabe6d6d1c647a57f8ee9ca96fa7a8afb9a5781559aa91058dd78998e72512bab0dd15270100000000000000\",\"5ce7f32c062f736c7573682f000000000315425426000000001976a9147c154ed1dc59609e3d26abb2df2ea3d587cd8c4188ac00000000000000002c6a4c2952534b424c4f434b3abccf9681cb9d53efbe0bd1619b627084ee670fb81a05dcad27829e32004bb3bb0000000000000000266a24aa21a9ed559cc5c19c1f18fd746f9cfd666fd3d5e616fdb93633ffaa5fa9497c24b8393600000000\",[\"b3e6c754292e856d4e51928a50e4542a8562c7fb9d995dc14f56c80d5449a8c8\",\"bcd90564783cc0fe8c9971384958d52ca5ccae8bc54f7f81109db6d44cc4b6a7\",\"e2ce8d28ce525a93f2aae37b48a3fab704009d798497b672c32a475c08df935d\",\"95f37077773d6bfbbd5f68eee672224aed8ca94102488038c5595a380a68d341\",\"2c5a47aaf763aa26b6d23077c4258cfdf8551f973b6b26f069a3a05ac9023045\",\"cf801d294e17ce5f5578315d011457e43aa1dca013cc8089b2774a68fa9624a0\",\"08f7592b032fd369c0b80ac59925cbf0e1e8eeb04f3dae303a011d9cafdc7b5e\",\"e0f9df26c43039892162da17dee75e2677194cf0947ac10b649e7f9c52fa61ef\",\"a74385fc3030cf10be3859fa9b901b3e828ae8260089d32f0818d8abfc3a1b0b\",\"29e05843383cdd7b41fc16c49339e50393bb98f6e54704d3d99ddaf14e604899\",\"00e69d2e6a2a28a336f49c41a8b784ef74586acba68e6852c151a96b137b490f\",\"9dd717edb99ecbad760d3d443cf559770691e7c86f92f687bcc7288b75a3d659\"],\"20000004\",\"1708417e\",\"63bee7ee\",true]}\n"
2023-01-11T16:46:44.065027Z  INFO translator::downstream_sv1::downstream: Receiving from Mining Device: "{\"method\": \"mining.submit\", \"params\": [\"xxxxxxx.cpu\", \"10\", \"000000000000\", \"63bee7ee\", \"008f0433\"], \"id\":4}"
2023-01-11T16:46:44.065704Z  INFO translator::downstream_sv1::downstream: Sending to Mining Device: "{\"id\":\"4\",\"error\":null,\"result\":true}\n"
2023-01-11T16:46:44.066238Z  INFO roles_logic_sv2::utils: reduce_path: coinbase_id: [210, 140, 91, 193, 222, 113, 189, 91, 246, 10, 196, 201, 207, 173, 109, 210, 147, 116, 210, 119, 223, 4, 105, 121, 148, 84, 236, 151, 177, 33, 32, 62]
Kind(
    UnexpectedEof,
)
thread 'async-std/runtime' panicked at 'Failed to receive from Upstream: RecvError', roles/translator/src/upstream_sv2/upstream.rs:214:50
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:100:14
   2: core::result::unwrap_failed
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/result.rs:1616:5
   3: core::result::Result<T,E>::expect
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/result.rs:1258:23
   4: translator::upstream_sv2::upstream::Upstream::parse_incoming::{{closure}}
             at ./src/upstream_sv2/upstream.rs:214:32
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/future/mod.rs:80:19
   6: <async_std::task::builder::SupportTaskLocals<F> as core::future::future::Future>::poll::{{closure}}
             at /home/stratum/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.12.0/src/task/builder.rs:199:17
   7: async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current::{{closure}}
             at /home/stratum/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.12.0/src/task/task_locals_wrapper.rs:60:13
   8: std::thread::local::LocalKey<T>::try_with
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/thread/local.rs:399:16
   9: std::thread::local::LocalKey<T>::with
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/thread/local.rs:375:9
  10: async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current
             at /home/stratum/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.12.0/src/task/task_locals_wrapper.rs:55:9
  11: <async_std::task::builder::SupportTaskLocals<F> as core::future::future::Future>::poll
             at /home/stratum/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.12.0/src/task/builder.rs:197:13
  12: async_executor::Executor::spawn::{{closure}}
             at /home/stratum/.cargo/registry/src/github.com-1ecc6299db9ec823/async-executor-1.4.1/src/lib.rs:144:13
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/future/mod.rs:80:19
  14: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/future/future.rs:119:9
  15: async_task::raw::RawTask<F,T,S>::run
             at /home/stratum/.cargo/registry/src/github.com-1ecc6299db9ec823/async-task-4.0.3/src/raw.rs:489:20
  16: async_task::runnable::Runnable::run
             at /home/stratum/.cargo/registry/src/github.com-1ecc6299db9ec823/async-task-4.0.3/src/runnable.rs:309:18
  17: async_executor::Executor::run::{{closure}}::{{closure}}
             at /home/stratum/.cargo/registry/src/github.com-1ecc6299db9ec823/async-executor-1.4.1/src/lib.rs:235:21
  18: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/future/mod.rs:80:19
  19: <futures_lite::future::Or<F1,F2> as core::future::future::Future>::poll
             at /home/stratum/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-lite-1.12.0/src/future.rs:529:33
  20: async_executor::Executor::run::{{closure}}
             at /home/stratum/.cargo/registry/src/github.com-1ecc6299db9ec823/async-executor-1.4.1/src/lib.rs:242:9
  21: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/future/mod.rs:80:19
  22: <futures_lite::future::Or<F1,F2> as core::future::future::Future>::poll
             at /home/stratum/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-lite-1.12.0/src/future.rs:529:33
  23: async_io::driver::block_on
             at /home/stratum/.cargo/registry/src/github.com-1ecc6299db9ec823/async-io-1.6.0/src/driver.rs:142:33
  24: async_global_executor::reactor::block_on::{{closure}}
             at /home/stratum/.cargo/registry/src/github.com-1ecc6299db9ec823/async-global-executor-2.0.2/src/reactor.rs:3:18
  25: async_global_executor::reactor::block_on
             at /home/stratum/.cargo/registry/src/github.com-1ecc6299db9ec823/async-global-executor-2.0.2/src/reactor.rs:12:5
  26: async_global_executor::threading::thread_main_loop::{{closure}}::{{closure}}
             at /home/stratum/.cargo/registry/src/github.com-1ecc6299db9ec823/async-global-executor-2.0.2/src/threading.rs:95:17
  27: std::thread::local::LocalKey<T>::try_with
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/thread/local.rs:399:16
  28: std::thread::local::LocalKey<T>::with
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/thread/local.rs:375:9
  29: async_global_executor::threading::thread_main_loop::{{closure}}
             at /home/stratum/.cargo/registry/src/github.com-1ecc6299db9ec823/async-global-executor-2.0.2/src/threading.rs:89:13
  30: std::panicking::try::do_call
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:403:40
  31: __rust_try
  32: std::panicking::try
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:367:19
  33: std::panic::catch_unwind
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panic.rs:133:14
  34: async_global_executor::threading::thread_main_loop
             at /home/stratum/.cargo/registry/src/github.com-1ecc6299db9ec823/async-global-executor-2.0.2/src/threading.rs:88:12
  35: core::ops::function::FnOnce::call_once
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

It did receive regular `Up: Set New Prev Hash` messages before this happened. After that panic those no longer come in.

I can't find anything in the spec about timeouts.

It should probably try to reconnect if this happens. Maybe upstream should complain and warn before hanging up?

**Comment by darricksee** [comment]
In this case I think the tproxy should:

1. drop all miner connections
2. try reconnecting with pool (or backup pool)?
3. re-open downstream listen port
4. re-accept miner connections

Does this sound reasonable?

**Comment by Sjors** [comment]
It does to me, but I've only tested with a CPU miner so far (which seems to automatically try to reconnect).

**Comment by GitGab19** [comment]
Closing this as stale
