### ISSUE TITLE
fix interop-jdc-change-upstream.jsonn test that does not pass remotely

### ISSUE THREAD

**Issue by lorbax** [stratum-mining/stratum#701]
This test passes locally but does not pass on github actions
/test/message-generator/test/interop-jdc-change-upstream.json
Currently it is just skipped from github actions, as we can see from the script message-genrator-test.sh

**Comment by pavlenex** [comment]
@plebhash Go for it :)

**Comment by plebhash** [comment]
@lorbax do you know what the error message on github actions is?

I'm trying to reproduce locally. The steps were:
1. check out `dev` branch
2. modify `message-genrator-tests.sh` to remove the logical filter around `interop-jdc-change-upstream.json`
3. use [`act`](https://github.com/nektos/act): `$ act -W '.github/workflows/coverage.yaml'`

can you confirm this is the error message?
```
$ act -W '.github/workflows/coverage.yaml'
WARN  ⚠ You are using Apple M-series chip and you have not specified container architecture, you might encounter issues while running act. If so, try running it with '--container-architecture linux/amd64'. ⚠  
[Test Coverage/Tarpaulin Test] 🚀  Start image=xd009642/tarpaulin:0.25.0-nightly
INFO[0000] Parallel tasks (0) below minimum, setting to 1 
[Test Coverage/Tarpaulin Test]   🐳  docker pull image=xd009642/tarpaulin:0.25.0-nightly platform= username= forcePull=true
INFO[0002] Parallel tasks (0) below minimum, setting to 1 
[Test Coverage/Tarpaulin Test]   🐳  docker create image=xd009642/tarpaulin:0.25.0-nightly platform= entrypoint=["tail" "-f" "/dev/null"] cmd=[] network="host"
[Test Coverage/Tarpaulin Test]   🐳  docker run image=xd009642/tarpaulin:0.25.0-nightly platform= entrypoint=["tail" "-f" "/dev/null"] cmd=[] network="host"
[Test Coverage/Tarpaulin Test]   ☁  git clone 'https://github.com/actions/upload-artifact' # ref=v3
[Test Coverage/Tarpaulin Test] ⭐ Run Main Checkout repository
[Test Coverage/Tarpaulin Test]   🐳  docker cp src=/Users/plebhash/develop/stratum/. dst=/Users/plebhash/develop/stratum
[Test Coverage/Tarpaulin Test]   ✅  Success - Main Checkout repository
[Test Coverage/Tarpaulin Test] ⭐ Run Main Generate code coverage
[Test Coverage/Tarpaulin Test]   🐳  docker exec cmd=[sh -e /var/run/act/workflow/1.sh] user= workdir=
| cargo 1.69.0-nightly (9d5b32f50 2023-02-22)
| Dec 22 22:11:56.961 DEBUG cargo_tarpaulin: set up logging
| Dec 22 22:11:56.966  INFO cargo_tarpaulin::config: Creating config
| Dec 22 22:13:12.117  WARN cargo_tarpaulin::config: Couldn't get project metadata `cargo metadata` exited with an error: warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
| package:   /Users/plebhash/develop/stratum/test/scale/Cargo.toml
| workspace: /Users/plebhash/develop/stratum/Cargo.toml
|     Updating crates.io index
| 
| Dec 22 22:13:12.132  INFO cargo_tarpaulin: Running config default
| Dec 22 22:13:12.132  INFO cargo_tarpaulin: Running Tarpaulin
| Dec 22 22:13:12.133  INFO cargo_tarpaulin: Building project
| Dec 22 22:13:52.046  WARN cargo_tarpaulin::config: Couldn't get project metadata `cargo metadata` exited with an error: warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
| package:   /Users/plebhash/develop/stratum/test/scale/Cargo.toml
| workspace: /Users/plebhash/develop/stratum/Cargo.toml
|     Updating git repository `https://github.com/diondokter/toml-rs`
|     Updating crates.io index
| 
| Dec 22 22:13:52.061  INFO cargo_tarpaulin::cargo: Cleaning project
| Dec 22 22:14:44.460 ERROR cargo_tarpaulin: Cargo failed to run! Error: `cargo metadata` exited with an error: warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
| package:   /Users/plebhash/develop/stratum/test/scale/Cargo.toml
| workspace: /Users/plebhash/develop/stratum/Cargo.toml
|     Updating crates.io index
| 
| Error: "Cargo failed to run! Error: `cargo metadata` exited with an error: warning: profiles for the non root package will be ignored, specify profiles at the workspace root:\npackage:   /Users/plebhash/develop/stratum/test/scale/Cargo.toml\nworkspace: /Users/plebhash/develop/stratum/Cargo.toml\n    Updating crates.io index\n"
[Test Coverage/Tarpaulin Test]   ❌  Failure - Main Generate code coverage
[Test Coverage/Tarpaulin Test] exitcode '1': failure
[Test Coverage/Tarpaulin Test] 🏁  Job failed
Error: Job 'Tarpaulin Test' failed

```

**Comment by plebhash** [comment]
I'm trying to reproduce the error so I can have a better understanding of what's going on.

I opened #704 so I could observe the behavior of Github Actions. This was the result: https://github.com/stratum-mining/stratum/actions/runs/7317145678/job/19932436452

But then I wanted to see if a local execution was successful, since @lorbax said:
> This test passes locally but does not pass on github actions

However, that was not what I observed. A local execution resulted in errors as well.
Additionally, the behavior is non-deterministic, and the error message changes across different executions.

Here are the commands I'm running locally:
```
$ cd utils/message-generator/
$ cargo run -- ../../test/message-generator/test/interop-jdc-change-upstream.json 
```

And here are some of the different error messages I saw:
```
...
STD ERR:      Running `target/llvm-cov-target/debug/jd_client -c ./test/config/interop-jd-change-upstream/jdc-config.toml`
STD OUT: 2023-12-25T03:34:49.481711Z  INFO jd_client::upstream_sv2::upstream: PROXY SERVER - ACCEPTING FROM UPSTREAM: 127.0.0.1:44254
STD OUT: 2023-12-25T03:34:49.486343Z  INFO roles_logic_sv2::handlers::common: Received SetupConnectionSuccess: version=2, flags=0
STD OUT: 2023-12-25T03:34:49.486366Z  INFO jd_client: Connected to Upstream!
STD OUT: 2023-12-25T03:34:49.487949Z  INFO jd_client::job_declarator: JD proxy: setupconnection Proxy address: 127.0.0.1:34265
STD OUT: 2023-12-25T03:34:49.488540Z ERROR network_helpers::noise_connection_tokio: Disconnected from client while reading : early eof - 127.0.0.1:34264
STD ERR: thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', roles/jd-client/src/job_declarator/setup_connection.rs:58:60
STD ERR: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
STD OUT: 2023-12-25T03:34:49.488871Z ERROR network_helpers::noise_connection_tokio: Disconnecting from client due to error receiving: receiving from an empty and closed channel - 127.0.0.1:34264
thread 'main' panicked at 'explicit panic', src/external_commands.rs:264:21
```

```
...
STD ERR:      Running `target/debug/mining-device`
STD OUT: start
thread 'main' panicked at 'explicit panic', src/external_commands.rs:264:21
```

@lorbax could you confirm that you are able to execute this test locally on your setup? Does it always succeed, even if you do it repeated times?

**Comment by lorbax** [comment]
This test is not passing right now. I observed the same error as yours
`STD ERR:     Finished dev [optimized + debuginfo] target(s) in 0.13s
STD ERR:      Running `target/llvm-cov-target/debug/jd_client -c ./test/config/interop-jd-change-upstream/jdc-config.toml`
STD OUT: 2024-01-03T11:18:06.265669Z  INFO jd_client::upstream_sv2::upstream: PROXY SERVER - ACCEPTING FROM UPSTREAM: 127.0.0.1:44254
STD OUT: 2024-01-03T11:18:06.271902Z  INFO roles_logic_sv2::handlers::common: Received SetupConnectionSuccess: version=2, flags=0
STD OUT: 2024-01-03T11:18:06.271919Z  INFO jd_client: Connected to Upstream!
thread 'main' panicked at 'explicit panic', src/external_commands.rs:237:21
`
I will dive into this as soon as I finish the rcp client for the mempool in the JD-server

**Comment by Fi3** [comment]
Note that when you run it directly in your machine and it fail the JDS do not get killed cause the test exit before reaching clean out messages, so when you re run it the port is not anymore free and the test fail for another reason. This is not an issue when you use a container to run the test but maybe we should address it (always execute clean up commands)

this could be the non deterministic think that you encountered.

**Comment by Fi3** [comment]
tried to run it several times and I can not get it to fail. If you run it locally a trick to check which port are not free is to use:
```
sudo netstat -tulpn  | grep target
```

**Comment by lorbax** [comment]
Thank you @Fi3, I'll handle this as soon as I have ready the pr about rpc client
